import jsPDF from 'jspdf'

export interface DocumentData {
  title: string
  content: string
  type: 'business_plan' | 'executive_summary' | 'marketing_plan'
  clientName?: string
  businessName?: string
  industry?: string
  generatedDate: string
}

export const generatePDF = async (doc: DocumentData): Promise<void> => {
  const pdfDoc = new jsPDF()
  const pageWidth = pdfDoc.internal.pageSize.getWidth()
  const pageHeight = pdfDoc.internal.pageSize.getHeight()
  const margin = 20
  const maxLineWidth = pageWidth - (margin * 2)
  
  let yPosition = margin

  // Add header with business info
  pdfDoc.setFontSize(20)
  pdfDoc.setFont('helvetica', 'bold')
  pdfDoc.text(doc.title, margin, yPosition)
  yPosition += 15

  if (doc.businessName) {
    pdfDoc.setFontSize(14)
    pdfDoc.setFont('helvetica', 'normal')
    pdfDoc.text(`Business: ${doc.businessName}`, margin, yPosition)
    yPosition += 10
  }

  if (doc.clientName) {
    pdfDoc.setFontSize(12)
    pdfDoc.text(`Prepared for: ${doc.clientName}`, margin, yPosition)
    yPosition += 10
  }

  if (doc.industry) {
    pdfDoc.text(`Industry: ${doc.industry}`, margin, yPosition)
    yPosition += 10
  }

  pdfDoc.setFontSize(10)
  pdfDoc.text(`Generated: ${doc.generatedDate}`, margin, yPosition)
  yPosition += 15

  // Add separator line
  pdfDoc.setLineWidth(0.5)
  pdfDoc.line(margin, yPosition, pageWidth - margin, yPosition)
  yPosition += 15

  // Add content
  pdfDoc.setFontSize(12)
  pdfDoc.setFont('helvetica', 'normal')
  
  // Split content into lines and handle page breaks
  const lines = pdfDoc.splitTextToSize(doc.content, maxLineWidth)
  
  for (let i = 0; i < lines.length; i++) {
    // Check if we need a new page
    if (yPosition > pageHeight - margin) {
      pdfDoc.addPage()
      yPosition = margin
    }
    
    pdfDoc.text(lines[i], margin, yPosition)
    yPosition += 7
  }

  // Add footer
  const totalPages = pdfDoc.getNumberOfPages()
  for (let i = 1; i <= totalPages; i++) {
    pdfDoc.setPage(i)
    pdfDoc.setFontSize(8)
    pdfDoc.text(
      `Generated by iDEAN AI - Page ${i} of ${totalPages}`,
      pageWidth - 80,
      pageHeight - 10
    )
  }

  // Save the PDF
  const fileName = `${doc.businessName || 'Document'}_${doc.type}.pdf`
  pdfDoc.save(fileName)
}

export const shareDocument = async (doc: DocumentData): Promise<string> => {
  // Generate a shareable URL (in a real app, this would save to a database)
  const shareId = Math.random().toString(36).substring(2, 15)
  const shareUrl = `${window.location.origin}/shared/${shareId}`
  
  // Store document temporarily in localStorage (in production, use a proper backend)
  localStorage.setItem(`shared_${shareId}`, JSON.stringify(doc))
  
  // Copy to clipboard
  try {
    await navigator.clipboard.writeText(shareUrl)
    return shareUrl
  } catch (err) {
    console.error('Failed to copy to clipboard:', err)
    return shareUrl
  }
}

export const formatContentForDisplay = (content: string): string => {
  // Convert markdown-like formatting to HTML
  return content
    .replace(/^# (.+)$/gm, '<h1 class="text-2xl font-bold mb-4 mt-6">$1</h1>')
    .replace(/^## (.+)$/gm, '<h2 class="text-xl font-semibold mb-3 mt-5">$1</h2>')
    .replace(/^### (.+)$/gm, '<h3 class="text-lg font-medium mb-2 mt-4">$1</h3>')
    .replace(/^\* (.+)$/gm, '<li class="ml-4">• $1</li>')
    .replace(/^- (.+)$/gm, '<li class="ml-4">• $1</li>')
    .replace(/\n\n/g, '</p><p class="mb-3">')
    .replace(/^/, '<p class="mb-3">')
    .replace(/$/, '</p>')
}

export const downloadAsText = (doc: DocumentData): void => {
  const content = `${doc.title}\n${'='.repeat(doc.title.length)}\n\n${doc.content}`
  const blob = new Blob([content], { type: 'text/plain' })
  const url = URL.createObjectURL(blob)
  
  const a = document.createElement('a')
  a.href = url
  a.download = `${doc.businessName || 'Document'}_${doc.type}.txt`
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}